window.PET_CATALOG = [
  {
    "id": 1,
    "name": "Pet Kitty",
    "titleStrId": 932,
    "mediaRefId": 1015,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 2,
    "name": "Pet Frog",
    "titleStrId": 939,
    "mediaRefId": 1014,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 3,
    "name": "Pet Ducky",
    "titleStrId": 937,
    "mediaRefId": 1013,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 4,
    "name": "Pet Puppy",
    "titleStrId": 938,
    "mediaRefId": 1020,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 5,
    "name": "Pet Butterfly",
    "titleStrId": 1389,
    "mediaRefId": 1088,
    "cost": 400,
    "isMember": true,
    "type": 1,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 6,
    "name": "Pet Hamster",
    "titleStrId": 1442,
    "mediaRefId": 1117,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 7,
    "name": "Pet Bat",
    "titleStrId": 1504,
    "mediaRefId": 1175,
    "cost": 400,
    "isMember": true,
    "type": 1,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 8,
    "name": "Pet Seahorse",
    "titleStrId": 1607,
    "mediaRefId": 1203,
    "cost": 400,
    "isMember": false,
    "type": 2,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 9,
    "name": "Pet Anglerfish",
    "titleStrId": 1606,
    "mediaRefId": 1202,
    "cost": 400,
    "isMember": true,
    "type": 2,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 10,
    "name": "Pet Reindeer",
    "titleStrId": 1652,
    "mediaRefId": 1210,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 11,
    "name": "Pet Snake",
    "titleStrId": 1730,
    "mediaRefId": 1226,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 12,
    "name": "Pet Jellyfish",
    "titleStrId": 1967,
    "mediaRefId": 1330,
    "cost": 400,
    "isMember": true,
    "type": 2,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 13,
    "name": "Pet Bunny",
    "titleStrId": 2130,
    "mediaRefId": 1403,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 14,
    "name": "Pet Hummingbird",
    "titleStrId": 2277,
    "mediaRefId": 1483,
    "cost": 400,
    "isMember": true,
    "type": 1,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 15,
    "name": "Pet Turtle",
    "titleStrId": 2667,
    "mediaRefId": 1633,
    "cost": 400,
    "isMember": true,
    "type": 4,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 16,
    "name": "Pet Monkey",
    "titleStrId": 2701,
    "mediaRefId": 1657,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 17,
    "name": "Pet Tarantula",
    "titleStrId": 2767,
    "mediaRefId": 1763,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 18,
    "name": "Pet Fox",
    "titleStrId": 2819,
    "mediaRefId": 1790,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 19,
    "name": "Pet Owl",
    "titleStrId": 2960,
    "mediaRefId": 1932,
    "cost": 400,
    "isMember": true,
    "type": 1,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 20,
    "name": "Pet Tiger",
    "titleStrId": 3010,
    "mediaRefId": 1959,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 21,
    "name": "Pet Arctic Wolf",
    "titleStrId": 3120,
    "mediaRefId": 2035,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 22,
    "name": "Pet Raccoon",
    "titleStrId": 3508,
    "mediaRefId": 2223,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 23,
    "name": "Pet Joey",
    "titleStrId": 10747,
    "mediaRefId": 2531,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 24,
    "name": "Pet Eagle",
    "titleStrId": 18050,
    "mediaRefId": 2691,
    "cost": 400,
    "isMember": true,
    "type": 1,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 25,
    "name": "Pet Cheetah",
    "titleStrId": 18168,
    "mediaRefId": 2719,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 26,
    "name": "Pet Rhino",
    "titleStrId": 18606,
    "mediaRefId": 2870,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 27,
    "name": "Pet Giraffe",
    "titleStrId": 18609,
    "mediaRefId": 2871,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 28,
    "name": "Pet Sugar Glider",
    "titleStrId": 18735,
    "mediaRefId": 2914,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 29,
    "name": "Pet Lion",
    "titleStrId": 18974,
    "mediaRefId": 3017,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 30,
    "name": "Pet Panda",
    "titleStrId": 19781,
    "mediaRefId": 3624,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 31,
    "name": "Pet Polar Bear",
    "titleStrId": 19883,
    "mediaRefId": 3663,
    "cost": 400,
    "isMember": true,
    "type": 4,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 32,
    "name": "Pet Gecko",
    "titleStrId": 20141,
    "mediaRefId": 3739,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 34,
    "name": "Pet Pony",
    "titleStrId": 21335,
    "mediaRefId": 3760,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 35,
    "name": "Pet Piglet",
    "titleStrId": 21546,
    "mediaRefId": 3815,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 36,
    "name": "Pet Ferret",
    "titleStrId": 23145,
    "mediaRefId": 4114,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 37,
    "name": "Pet Elephant",
    "titleStrId": 22815,
    "mediaRefId": 4115,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 38,
    "name": "Pet Armadillo",
    "titleStrId": 22814,
    "mediaRefId": 4116,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 39,
    "name": "Pet Peacock",
    "titleStrId": 22816,
    "mediaRefId": 4117,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 40,
    "name": "Pet Honeybee",
    "titleStrId": 23322,
    "mediaRefId": 4147,
    "cost": 400,
    "isMember": false,
    "type": 1,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 41,
    "name": "Pet Rooster",
    "titleStrId": 28653,
    "mediaRefId": 5548,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 42,
    "name": "Pet Skunk",
    "titleStrId": 23970,
    "mediaRefId": 4348,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 43,
    "name": "Pet Turkey",
    "titleStrId": 24079,
    "mediaRefId": 4403,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 44,
    "name": "Pet Penguin",
    "titleStrId": 24289,
    "mediaRefId": 4436,
    "cost": 400,
    "isMember": false,
    "type": 4,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 45,
    "name": "Pet Snow Leopard",
    "titleStrId": 24312,
    "mediaRefId": 4448,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 46,
    "name": "Pet Mantis",
    "titleStrId": 24590,
    "mediaRefId": 4533,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 47,
    "name": "Pet Ladybug",
    "titleStrId": 24592,
    "mediaRefId": 4534,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 48,
    "name": "Pet Grasshopper",
    "titleStrId": 24594,
    "mediaRefId": 4535,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 49,
    "name": "Pet Squirrel",
    "titleStrId": 24595,
    "mediaRefId": 4536,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 50,
    "name": "Pet Mouse",
    "titleStrId": 24596,
    "mediaRefId": 4537,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 51,
    "name": "Pet Firefly",
    "titleStrId": 24612,
    "mediaRefId": 4554,
    "cost": 400,
    "isMember": false,
    "type": 1,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 52,
    "name": "Pet Lemur",
    "titleStrId": 24695,
    "mediaRefId": 4598,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 53,
    "name": "Pet Hippo",
    "titleStrId": 24790,
    "mediaRefId": 4619,
    "cost": 400,
    "isMember": true,
    "type": 4,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 54,
    "name": "Pet Goat",
    "titleStrId": 25144,
    "mediaRefId": 4798,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 55,
    "name": "Pet Meerkat",
    "titleStrId": 25446,
    "mediaRefId": 4902,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 56,
    "name": "Pet Golden Bunny",
    "titleStrId": 25863,
    "mediaRefId": 5065,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 57,
    "name": "Pet Phantom",
    "titleStrId": 27484,
    "mediaRefId": 5126,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 58,
    "name": "Pet Seal",
    "titleStrId": 27759,
    "mediaRefId": 5258,
    "cost": 400,
    "isMember": false,
    "type": 4,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 59,
    "name": "Pet Otter",
    "titleStrId": 27760,
    "mediaRefId": 5259,
    "cost": 400,
    "isMember": false,
    "type": 4,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 60,
    "name": "Rare Pet Phantom",
    "titleStrId": 27817,
    "mediaRefId": 5280,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 4,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 61,
    "name": "Pet Groundhog",
    "titleStrId": 27946,
    "mediaRefId": 5306,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 62,
    "name": "Pet Llama",
    "titleStrId": 28106,
    "mediaRefId": 5444,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 63,
    "name": "Pet Arctic Fox",
    "titleStrId": 28630,
    "mediaRefId": 5541,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 64,
    "name": "Pet Hyena",
    "titleStrId": 28906,
    "mediaRefId": 5711,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 65,
    "name": "Pet Sloth",
    "titleStrId": 30655,
    "mediaRefId": 6274,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 66,
    "name": "Pet Dove",
    "titleStrId": 30654,
    "mediaRefId": 6273,
    "cost": 400,
    "isMember": false,
    "type": 1,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 67,
    "name": "Pet Baby Chick",
    "titleStrId": 29367,
    "mediaRefId": 5783,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": true
  },
  {
    "id": 68,
    "name": "Pet Golden Armadillo",
    "titleStrId": 29420,
    "mediaRefId": 5786,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 69,
    "name": "Pet Falcon",
    "titleStrId": 29535,
    "mediaRefId": 5803,
    "cost": 400,
    "isMember": true,
    "type": 1,
    "status": 0,
    "isReward": false,
    "isEgg": true
  },
  {
    "id": 70,
    "name": "Pet Crocodile",
    "titleStrId": 29536,
    "mediaRefId": 5804,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": true
  },
  {
    "id": 71,
    "name": "Pet Platypus",
    "titleStrId": 29803,
    "mediaRefId": 5873,
    "cost": 400,
    "isMember": true,
    "type": 4,
    "status": 0,
    "isReward": false,
    "isEgg": true
  },
  {
    "id": 72,
    "name": "Pet Phantom",
    "titleStrId": 27484,
    "mediaRefId": 5126,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 73,
    "name": "Pet Golden Pony",
    "titleStrId": 30728,
    "mediaRefId": 6326,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 74,
    "name": "Pet Shark",
    "titleStrId": 29966,
    "mediaRefId": 5947,
    "cost": 400,
    "isMember": true,
    "type": 2,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 75,
    "name": "Pet Dolphin",
    "titleStrId": 30111,
    "mediaRefId": 6011,
    "cost": 400,
    "isMember": true,
    "type": 2,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 76,
    "name": "Pet Echidna",
    "titleStrId": 30415,
    "mediaRefId": 6188,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": true
  },
  {
    "id": 77,
    "name": "Pet Koala",
    "titleStrId": 30566,
    "mediaRefId": 6257,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 80,
    "name": "Pet Lynx",
    "titleStrId": 31017,
    "mediaRefId": 6530,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 81,
    "name": "Pet Octopus",
    "titleStrId": 31064,
    "mediaRefId": 6569,
    "cost": 400,
    "isMember": true,
    "type": 2,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 82,
    "name": "Pet Fennec Fox",
    "titleStrId": 31065,
    "mediaRefId": 6570,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 0,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 83,
    "name": "Pet Hedgehog",
    "titleStrId": 31066,
    "mediaRefId": 6571,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 0,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 84,
    "name": "Pet Scorpion",
    "titleStrId": 31139,
    "mediaRefId": 6591,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 85,
    "name": "Pet Crow",
    "titleStrId": 31484,
    "mediaRefId": 6720,
    "cost": 400,
    "isMember": true,
    "type": 1,
    "status": 0,
    "isReward": false,
    "isEgg": true
  },
  {
    "id": 86,
    "name": "Pet Moose",
    "titleStrId": 31646,
    "mediaRefId": 6804,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 87,
    "name": "Pet Poodle",
    "titleStrId": 32080,
    "mediaRefId": 6994,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 88,
    "name": "Pet Love Bunny",
    "titleStrId": 32095,
    "mediaRefId": 6996,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 89,
    "name": "Pet Sabertooth",
    "titleStrId": 32543,
    "mediaRefId": 7185,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 90,
    "name": "Pet Direwolf",
    "titleStrId": 32829,
    "mediaRefId": 7279,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 91,
    "name": "Pet Dodo",
    "titleStrId": 32919,
    "mediaRefId": 7329,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 92,
    "name": "Pet Fantasy Peacock",
    "titleStrId": 32957,
    "mediaRefId": 7332,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 93,
    "name": "Pet Millipede",
    "titleStrId": 33336,
    "mediaRefId": 7494,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": true
  },
  {
    "id": 94,
    "name": "Pet Poodle Moth",
    "titleStrId": 33335,
    "mediaRefId": 7495,
    "cost": 400,
    "isMember": true,
    "type": 1,
    "status": 0,
    "isReward": false,
    "isEgg": true
  },
  {
    "id": 95,
    "name": "Pet Vulture",
    "titleStrId": 33334,
    "mediaRefId": 7496,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": true
  },
  {
    "id": 96,
    "name": "Pet Coyote",
    "titleStrId": 33547,
    "mediaRefId": 7577,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 97,
    "name": "Meagyn's Pet Bear",
    "titleStrId": 33662,
    "mediaRefId": 7606,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 99,
    "name": "Pet Lovebug",
    "titleStrId": 33891,
    "mediaRefId": 7719,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 100,
    "name": "Pet Flying Pig",
    "titleStrId": 34107,
    "mediaRefId": 7802,
    "cost": 400,
    "isMember": true,
    "type": 1,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 101,
    "name": "Pet Sparrow",
    "titleStrId": 34179,
    "mediaRefId": 7840,
    "cost": 400,
    "isMember": true,
    "type": 1,
    "status": 0,
    "isReward": false,
    "isEgg": true
  },
  {
    "id": 102,
    "name": "Pet Fennec Fox",
    "titleStrId": 31065,
    "mediaRefId": 6570,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 103,
    "name": "Pet Cardinal",
    "titleStrId": 34333,
    "mediaRefId": 7884,
    "cost": 400,
    "isMember": true,
    "type": 1,
    "status": 0,
    "isReward": false,
    "isEgg": true
  },
  {
    "id": 104,
    "name": "Pet Frilled Lizard",
    "titleStrId": 34396,
    "mediaRefId": 7915,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": true
  },
  {
    "id": 105,
    "name": "Pet Dragonfly",
    "titleStrId": 34559,
    "mediaRefId": 7957,
    "cost": 400,
    "isMember": true,
    "type": 1,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 106,
    "name": "Pet Magenta Seal",
    "titleStrId": 34675,
    "mediaRefId": 7997,
    "cost": 400,
    "isMember": false,
    "type": 4,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 107,
    "name": "Pet Pangolin",
    "titleStrId": 34676,
    "mediaRefId": 7998,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 108,
    "name": "Pet Camel",
    "titleStrId": 34879,
    "mediaRefId": 8040,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 109,
    "name": "Pet Snail",
    "titleStrId": 34880,
    "mediaRefId": 8041,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 110,
    "name": "Pet Galactic Firefly",
    "titleStrId": 35181,
    "mediaRefId": 8169,
    "cost": 400,
    "isMember": false,
    "type": 1,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 111,
    "name": "Pet Caterpillar",
    "titleStrId": 35667,
    "mediaRefId": 8300,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 112,
    "name": "Pet Lamb",
    "titleStrId": 36050,
    "mediaRefId": 8436,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 113,
    "name": "Pet Golden Reindeer",
    "titleStrId": 38870,
    "mediaRefId": 9124,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 114,
    "name": "Pet Highland Cow",
    "titleStrId": 39400,
    "mediaRefId": 9195,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 115,
    "name": "Pet Nighthawk",
    "titleStrId": 39569,
    "mediaRefId": 9241,
    "cost": 400,
    "isMember": true,
    "type": 1,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 116,
    "name": "Pet Frankenkitty",
    "titleStrId": 39637,
    "mediaRefId": 9243,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 117,
    "name": "Pet Fawn",
    "titleStrId": 39786,
    "mediaRefId": 9281,
    "cost": 400,
    "isMember": true,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 118,
    "name": "Exclusive Pet Phantom",
    "titleStrId": 39787,
    "mediaRefId": 9282,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 4,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 119,
    "name": "Pet Lunar Pony",
    "titleStrId": 39966,
    "mediaRefId": 9297,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 120,
    "name": "Pet Axolotl",
    "titleStrId": 40242,
    "mediaRefId": 9351,
    "cost": 400,
    "isMember": false,
    "type": 2,
    "status": 0,
    "isReward": false,
    "isEgg": false
  },
  {
    "id": 121,
    "name": "Count Fabulous (Cat)",
    "titleStrId": 40485,
    "mediaRefId": 9386,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 0,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 122,
    "name": "Count Fabulous (Bat)",
    "titleStrId": 40526,
    "mediaRefId": 9405,
    "cost": 400,
    "isMember": false,
    "type": 1,
    "status": 0,
    "isReward": true,
    "isEgg": false
  },
  {
    "id": 123,
    "name": "Tut",
    "titleStrId": 40608,
    "mediaRefId": 9406,
    "cost": 400,
    "isMember": false,
    "type": 0,
    "status": 0,
    "isReward": true,
    "isEgg": false
  }
];
